FROM nextcloud:17.0.9-apache
MAINTAINER Zweihänder

RUN apt-get update && apt-get install -y \
    supervisor \
  && rm -rf /var/lib/apt/lists/* \
  && mkdir /var/log/supervisord /var/run/supervisord

COPY supervisord-nextcloud.conf /etc/supervisor/supervisord.conf

ADD neith.crt /usr/local/share/ca-certificates/neith.crt
RUN update-ca-certificates

ENV NEXTCLOUD_UPDATE=1

CMD ["/usr/bin/supervisord"]

# TODO remove crt and remove it from git logs
