FROM  jedisct1/dnscrypt-server
MAINTAINER Zweihänder

# cron.sh dependencies
RUN set -ex; \
    apk add --no-cache bind-tools; \
    rm /var/spool/cron/crontabs/root; \
    mkdir -p /var/spool/cron/crontabs /etc/service/unboundCron;

COPY cron-dnscrypt-server-docker.sh /etc/service/unboundCron/run

RUN chmod +x /etc/service/unboundCron/run
