---
name: Publish zweizs/android-connectivity-check
"on":
  push:
    branches:
      - "master"
    tags:
      - "android/v*"
    paths:
      - "android-connectivity-check/**"
      - "!android-connectivity-check/README.md"
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:android-connectivity-check"
          push: true
          tags: zweizs/android-connectivity-check:latest
