name: Publish zweizs/anki-sync-server
"on":
  push:
    branches:
      - "master"
    tags:
      - "anki-sync-server/v*"
    paths:
      - "anki-sync-server/**"
      - "!anki-sync-server/README.md"
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: zweizs/anki-sync-server
          tags: |
            type=match,pattern=anki-sync-server-v(\d+.\d+.\d+-\d+),group=1
            type=match,pattern=anki-sync-server-v(\d+.\d+.\d+),group=1
            type=match,pattern=anki-sync-server-v(\d+.\d+),group=1
            type=raw,value={{date 'YYYYMMDD'}}
            type=raw,latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:anki-sync-server"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
