---
name: Publish zweizs/docker-fetchmail-plus-msmtp
"on":
  push:
    branches:
      - "master"
    tags:
      - "fetchmail/v*"
    paths:
      - "fetchmail-plus-msmtp/**"
      - "!fetchmail-plus-msmtp/README.md"
  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:fetchmail-plus-msmtp"
          push: true
          tags: zweizs/docker-fetchmail-plus-msmtp:latest
