---
name: Publish zweizs/docker-nextcloud-plus-cron
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 18 2 * *" # monthly, 2nd, at 1 est
  push:
    branches:
      - "master"
    tags:
      - "nextcloud/v*"
    paths:
      - "nextcloud-plus-cron/**"
      - "!nextcloud-plus-cron/README.md"

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: zweizs/docker-nextcloud-plus-cron
          tags: |
            type=match,pattern=nextcloud-v(\d+.\d+.\d+),group=1
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:nextcloud-plus-cron"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
