---
name: Publish DockerHub image
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * 4" # thurs 1pm est
  push:
    branches:
      - "master"
    tags:
      - "v*"
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "*.md"

jobs:
  build-container:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: zweizs/docker-nginx-proxy-plus-stream
          tags: >
            type=semver,pattern={{version}}\n
            type=semver,pattern={{major}}.{{minor}}\n
            type=schedule,pattern={{date 'YYYYMMDD'}}\n
            type=raw,value=latest,enable=
            ${{ endsWith(github.ref, github.event.repository.default_branch) }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
